In [99]:
import pandas as pd

In [2]:
file = open("../data/hotel_reviews.txt", "r")

In [189]:
data = pd.DataFrame(columns=["hotel_url", "author", "date", "rating", "title", "text"])

Empty DataFrame
Columns: [hotel_url, author, date, rating, title, text]
Index: []

In [191]:
for line in file.readlines():
    line = eval(line)
    line.pop("property_dict")
    line["text"] = str(line["text"]).encode('utf-16', 'surrogatepass').decode('utf-16')
    lk = pd.DataFrame(line,
                    columns=["hotel_url", "author", "date", "rating", "title", "text"],
                    index=pd.RangeIndex(0,1))
    data = pd.concat([data, lk], ignore_index=True)

In [206]:
d.to_csv("data/trip_advisor_data_chunk_10000k.csv", index=False, header=True, encoding='utf-16')

In [210]:
rating_5 = data[data["rating"] == 5].head(2245)

In [209]:
rating_lessthan_3 = data[data["rating"] <= 3]
rating_lessthan_3

,hotel_url,author,date,rating,title,text
5,Hotel_Review-g303503-d1735469-Reviews-Pousada_...,LiliT0URS,2019-02-01T00:00:00,3.0,Honest place to spend a couple of nights,This pousada is not too close to the downtown ...
12,Hotel_Review-g303503-d1735469-Reviews-Pousada_...,MatheusMedrado,2015-10-01T00:00:00,3.0,Stay,"The attendance is very good, but faced issues ..."
39,Hotel_Review-g644280-d1821178-Reviews-Agrituri...,hbayley,2015-03-01T00:00:00,3.0,Chilly on a winter's night,"When traveling to Tuscany in winter, please kn..."
56,Hotel_Review-g312848-d4173038-Reviews-Villa_Hu...,gaylem113,2019-03-01T00:00:00,3.0,Huge campus-convention location with three bed...,"Our location had only breakfast facility, whic..."
57,Hotel_Review-g312848-d4173038-Reviews-Villa_Hu...,825jaimeh,2019-02-01T00:00:00,3.0,"Good rooms, painful internet",I stayed two nights at the hotel on my own whi...
...,...,...,...,...,...,...
10943,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,amygH4552PQ,2017-04-01T00:00:00,3.0,Too expensive for what it is..,We stayed for here for our wedding night and I...
10950,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,950kt,2017-04-01T00:00:00,1.0,Bad experience at the Old Clare Hotel,"I stayed one night in late March, 2017 for bus..."
10953,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,tmhCanberra,2017-04-01T00:00:00,3.0,Weekend getaway,Beautiful hotel but far toooo expensive for 2k...
10959,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,Daoda2,2017-04-01T00:00:00,2.0,Paaartyyyy!!!,Great place to stay if this is what you want t...
10964,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,S4005JWchristinal,2017-03-01T00:00:00,1.0,Renovation works ongoing during my stay,"During my 5 day stay at the Old Clare, there w..."

In [211]:
d = pd.concat([rating_5, rating_lessthan_3], ignore_index=True)
d

,hotel_url,author,date,rating,title,text
0,Hotel_Review-g194775-d1121769-Reviews-Hotel_Ba...,Lagaiuzza,2016-01-01T00:00:00,5.0,"Baltic, what else?",We have spent in this hotel our summer holiday...
1,Hotel_Review-g194775-d1121769-Reviews-Hotel_Ba...,ashleyn763,2014-10-01T00:00:00,5.0,Excellent in every way!,I visited Hotel Baltic with my husband for som...
2,Hotel_Review-g194775-d1121769-Reviews-Hotel_Ba...,DavideMauro,2014-08-01T00:00:00,5.0,The house of your family's holiday,I've travelled quite a numbers of hotels but t...
3,Hotel_Review-g303503-d1735469-Reviews-Pousada_...,TwoMonkeysTravel,2017-03-01T00:00:00,5.0,Natural Luxury,"The property is surrounded by trees, which are..."
4,Hotel_Review-g303503-d1735469-Reviews-Pousada_...,analuizade,2016-09-01T00:00:00,5.0,Very cozy!,I had a very pleasant stay at this hotel! All ...
...,...,...,...,...,...,...
4485,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,amygH4552PQ,2017-04-01T00:00:00,3.0,Too expensive for what it is..,We stayed for here for our wedding night and I...
4486,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,950kt,2017-04-01T00:00:00,1.0,Bad experience at the Old Clare Hotel,"I stayed one night in late March, 2017 for bus..."
4487,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,tmhCanberra,2017-04-01T00:00:00,3.0,Weekend getaway,Beautiful hotel but far toooo expensive for 2k...
4488,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,Daoda2,2017-04-01T00:00:00,2.0,Paaartyyyy!!!,Great place to stay if this is what you want t...
4489,Hotel_Review-g255060-d8649358-Reviews-The_Old_...,S4005JWchristinal,2017-03-01T00:00:00,1.0,Renovation works ongoing during my stay,"During my 5 day stay at the Old Clare, there w..."

In [212]:
nlp

NameError: name 'nlp' is not defined